export const BUSINESS = {
  name: "Elarenza",
  tagline: "Your Signature Scent",
  addressLines: ["Wattala", "Wattala, Sri Lanka, 11300"],
  phoneDisplay: "+94 75 090 8002",
  phoneWhatsApp: "94750908002",
};

export const SRI_LANKA_DISTRICTS = [
  "Colombo",
  "Gampaha",
  "Kalutara",
  "Kandy",
  "Matale",
  "Nuwara Eliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  "Batticaloa",
  "Ampara",
  "Trincomalee",
  "Kurunegala",
  "Puttalam",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Moneragala",
  "Ratnapura",
  "Kegalle",
];
